- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Platforms(45ef3d11-7684-484d-8cc6-80df6d71edbc)'
    subscriptionId: '45ef3d11-7684-484d-8cc6-80df6d71edbc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devops.springhouse.com'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/speedglide/devopsdemo/blob/master/template.json'
    csmParametersFileLink: 'https://github.com/speedglide/devopsdemo/blob/master/parameters.json'
    deploymentMode: 'Complete'
    deploymentName: 'test'
