# Starter pipeline
 -task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN Platforms(45ef3d11-7684-484d-8cc6-80df6d71edbc)'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'https://github.com/speedglide/devopsdemo/blob/master/DeployResourceGroups.ps1'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- task: AzureCLI@2
  inputs:
    azureSubscription: 'MSDN Platforms(45ef3d11-7684-484d-8cc6-80df6d71edbc)'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'https://github.com/speedglide/devopsdemo/blob/master/DeployResourceGroups.ps1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Platforms(45ef3d11-7684-484d-8cc6-80df6d71edbc)'
    subscriptionId: '45ef3d11-7684-484d-8cc6-80df6d71edbc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DevOps.springhouse.com'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
